main: fr.peaceandcube.pacutilities.PACUtilities
name: PACUtilities
description: A plugin adding various commands and features
version: ${version}
author: YanisBft
website: https://github.com/PeaceAndCubeMC/PACUtilities
api-version: 1.19

depend: [pAcPI, Essentials]

commands:
  dispatchevent:
    description: Allows you to dispatch an event
    permission: pacutilities.dispatchevent
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/dispatchevent <type> <player> <name>"
  pacutilities:
    description: Reload the plugin
    permission: pacutilities.pacutilities
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/pacutilities reload"
  reglesevent:
    description: Allows you to read event rules
    permission: pacutilities.reglesevent
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/reglesevent <event>"
  spawndragon:
    description: Allows you to start a dragon fight
    permission: pacutilities.spawndragon
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/spawndragon [<minplayercount>] [<radiustocheck>]"
  tickettete:
    description: Allows you to add or remove tickets tete
    permission: pacutilities.tickettete
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/tickettete <add|remove> <player> [<amount>]"
  togglemsgsound:
    description: Allows you to enable or disable message sounds
    permission: pacutilities.togglemsgsound
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/togglemsgsound"

permissions:
  pacutilities.dispatchevent:
    description: Allows you to use /dispatchevent command
    default: op
  pacutilities.pacutilities:
    description: Allows you to use /pacutilities command
    default: op
  pacutilities.reglesevent:
    description: Allows you to use /reglesevent command
    default: true
  pacutilities.spawndragon:
    description: Allows you to use /spawndragon command
    default: op
  pacutilities.tickettete:
    description: Allows you to use /tickettete command
    default: op
  pacutilities.togglemsgsound:
    description: Allows you to use /togglemsgsound command
    default: true
